name: Automatic builds

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'contrib/**'
      - '**/*.md'

jobs:
  build:
    name: ${{ matrix.name }}

    env:
      MAKEJOBS: "-j3"

    strategy:
      fail-fast: false
      matrix:
        name:
        - x86_64-linux
        - x86_64-windows
        include:
          - name: x86_64-linux
            host: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            packages: libevent-dev
            config-opts: '--without-gui --disable-tests CPPFLAGS="-I$HOME/unix-bin/include" LDFLAGS="-L$HOME/unix-bin/lib" --with-boost-libdir --with-boost-libdir="$HOME/unix-bin/lib"'
            strip-command: "strip"
            build-deps-command: "./contrib/compilepackages-unix.sh"
          - name: x86_64-windows
            host: x86_64-w64-mingw32
            os: ubuntu-20.04
            packages: python3 nsis g++-mingw-w64-x86-64 wine64 bc wine-binfmt libevent-dev
            postinstall: |
              sudo update-alternatives --set x86_64-w64-mingw32-gcc  /usr/bin/x86_64-w64-mingw32-gcc-posix
              sudo update-alternatives --set x86_64-w64-mingw32-g++  /usr/bin/x86_64-w64-mingw32-g++-posix
              sudo update-binfmts --import /usr/share/binfmts/wine
            config-opts: '--without-gui --disable-tests --host=x86_64-w64-mingw32 CPPFLAGS="-I$HOME/mingw-bin/include" LDFLAGS="-L$HOME/mingw-bin/lib" --with-boost-libdir="$HOME/mingw-bin/lib"'
            strip-command: "x86_64-w64-mingw32-strip"
            build-deps-command: "./contrib/compilepackages-mingw.sh"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
          sudo apt-get install ${{ matrix.packages }}

      - name: Get source code
        uses: actions/checkout@v2
        
      - name: Build depends
        run: |
          chmod 755 -R .
          ${{ matrix.build-deps-command }}

      - name: Build Bunkercoin
        run: |
          ./autogen.sh
          ./configure ${{ matrix.config-opts }}
          make $MAKEJOBS
          
      - name: Strip built binaries
        run: |
          ${{ matrix.strip-command }} src/bunkercoin-cli src/bunkercoind src/bunkercoin-cli.exe src/bunkercoind.exe
          
      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: |
            src/bunkercoin-cli
            src/bunkercoind
            src/bunkercoin-cli.exe
            src/bunkercoind.exe
